### ISSUE TITLE
missing tables - web version

### ISSUE THREAD

**Issue by marinemoleco** [JulesBlm/TernaryPlot.com#1]
Hi,
until recently the page worked for me. Now all tables are missing and I cannot enter any data right now.
I tried:
Brave Version 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)
Chrome 74.0.3729.169 (Official Build) (64-bit)
Safari Version 11.1 (13605.1.33.1.2)
on macOS 10.13.4
Cheers

Edit:
Brave console message:
Resource interpreted as Stylesheet but transferred with MIME type application/javascript: "https://d33wubrfki0l68.cloudfront.net/js/adc83b19e793491b1c6ea0fd8b46cd9f32e592fc/msalign/assets/javascripts/modernizr.74668098.js".
app.bundle.js:21 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at Module.<anonymous> (app.bundle.js:21)
    at n (app.bundle.js:1)
    at app.bundle.js:1
    at app.bundle.js:1

**Comment by JulesBlm** [comment]
Hi there, sorry for the late response I only saw your issue just now. Unfortunately I am not able to reproduce the bug in the latest Chrome or Safari on macOS 10.14.2. Are the tables still not loading for you presently?

Cheers, Jules
