### ISSUE TITLE
Graph not updating

### ISSUE THREAD

**Issue by thjungers** [JulesBlm/TernaryPlot.com#44]
Hi,

I've just found your website. It doesn't seem to be working.
The graph is empty and I can't fill it, neither by editing the default values nor adding some.
Downloading the SVG file also gives and empty graph.
See this screenshot:
![image](https://user-images.githubusercontent.com/31347150/74655124-25393980-518c-11ea-966c-2694c2370c56.png)

I'm using Chrome 64-bit v.79.0.3945.130 on Windows 10.

Thanks,
Thomas

**Comment by JulesBlm** [comment]
Hi Thomas, thanks for reporting your issue, apologies that it's not working like it should. Could you open the console (View > Developer > JavaScript Console in Chrome) and tell me if you see an error there. If you please copy it here.  Thanks, Jules

**Comment by thjungers** [comment]
Hi Jules, 
Nope, nothing.
The console is empty.
Thomas

**Comment by JulesBlm** [comment]
Thanks for your swift response! Very strange, you could try the following things

- Does this happen with both default values as with custom values?
- Does hitting the plot button below the Areas and/or Lines table do anything?
- Can you try completely clearing the points table, entering 0.4, 0.4, 0.3 in the first row and pressing 'Plot points'. Do you see a point appearing?
- You can try plotting from an Incognito window to check if any browsers extensions are interfering. 

If any of these did the trick, please let me know.
Jules

**Comment by JulesBlm** [comment]
Without a further reponse, I'll close this issue
