### ISSUE TITLE
Broken "explanation page" link in new-visitor blurb

### ISSUE THREAD

**Issue by eternaleye** [JulesBlm/TernaryPlot.com#66]
The new visitor blurb links to `https://www.ternaryplot.com/%E2%80%9Cexplain.html%E2%80%9D` for its explanation page (smart quotes around `explain.html`), which results in a broken link.

**Comment by JulesBlm** [comment]
Thanks for the notification, I will fix it right away!

**Comment by JulesBlm** [comment]
It's fixed.
